language: "perl"
perl:
  - "5.20"

install:
    - cpanm Outthentic

script: "cpanm --installdeps . && perl Makefile.PL && make test && sudo make install && sparrow index update && strun --root t/ --match_l 200"
